# Generated by Django 4.2.2 on 2023-06-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_group',
        ),
        migrations.AddField(
            model_name='message',
            name='message_group',
            field=models.ManyToManyField(to='emailsender.group'),
        ),
    ]
