# Generated by Django 4.2.2 on 2023-06-20 07:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0005_message_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('sent', django.db.models.manager.Manager()),
            ],
        ),
    ]
