# Generated by Django 4.2.2 on 2023-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsender', '0006_alter_message_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_group',
            field=models.ManyToManyField(related_name='groups', to='emailsender.group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('ST', 'Sent')], default='DF', max_length=2),
        ),
    ]
